package com.everypaisa.tracker.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val md_theme_light_primary = Color(0xFF1B6B4A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA4F3C7)
val md_theme_light_onPrimaryContainer = Color(0xFF002112)
val md_theme_light_secondary = Color(0xFF4E6355)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E8D6)
val md_theme_light_onSecondaryContainer = Color(0xFF0B1F14)
val md_theme_light_tertiary = Color(0xFF3B6471)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBFE9F8)
val md_theme_light_onTertiaryContainer = Color(0xFF001F28)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DB)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF727970)

// Dark Theme Colors
val md_theme_dark_primary = Color(0xFF89D6AC)
val md_theme_dark_onPrimary = Color(0xFF003822)
val md_theme_dark_primaryContainer = Color(0xFF005234)
val md_theme_dark_onPrimaryContainer = Color(0xFFA4F3C7)
val md_theme_dark_secondary = Color(0xFFB5CBBB)
val md_theme_dark_onSecondary = Color(0xFF203528)
val md_theme_dark_secondaryContainer = Color(0xFF374B3E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E8D6)
val md_theme_dark_tertiary = Color(0xFFA3CDDC)
val md_theme_dark_onTertiary = Color(0xFF033542)
val md_theme_dark_tertiaryContainer = Color(0xFF224C59)
val md_theme_dark_onTertiaryContainer = Color(0xFFBFE9F8)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val md_theme_dark_outline = Color(0xFF8B938A)

// Semantic Colors
val IncomeGreen = Color(0xFF2E7D32)
val IncomeGreenDark = Color(0xFF81C784)
val ExpenseRed = Color(0xFFC62828)
val ExpenseRedDark = Color(0xFFEF9A9A)
val CreditBlue = Color(0xFF1565C0)
val CreditBlueDark = Color(0xFF64B5F6)
val TransferGray = Color(0xFF546E7A)
val TransferGrayDark = Color(0xFF90A4AE)
val InvestmentPurple = Color(0xFF6A1B9A)
val InvestmentPurpleDark = Color(0xFFCE93D8)

// Category Colors (Fixed - not affected by dynamic theming)
val CategoryFoodDining = Color(0xFFFC8019)
val CategoryGroceries = Color(0xFF5AC85A)
val CategoryShopping = Color(0xFFE91E63)
val CategoryTransportation = Color(0xFF29B6F6)
val CategoryBills = Color(0xFFFFA726)
val CategoryEntertainment = Color(0xFFAB47BC)
val CategoryHealthcare = Color(0xFFEF5350)
val CategoryEducation = Color(0xFF42A5F5)
val CategoryPersonalCare = Color(0xFFEC407A)
val CategoryTravel = Color(0xFF26C6DA)
val CategoryInvestments = Color(0xFF66BB6A)
val CategorySubscriptions = Color(0xFF7E57C2)
val CategoryTransfers = Color(0xFF78909C)
val CategorySalary = Color(0xFF4CAF50)
val CategoryRefunds = Color(0xFF8BC34A)
val CategoryCashback = Color(0xFFCDDC39)
val CategoryOthers = Color(0xFFBDBDBD)
